import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SuperMall",
  description: "Generated by Mahiman",
  icons: {
    icon: "/building.svg"
  }
};

export default function RootLayout({ children }) {
  return (
    // suppressHydrationWarning used because some browser extensions may modify
    // the <html> element before React hydrates, causing a non-actionable
    // hydration mismatch warning in development.
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
